### ISSUE TITLE
Instructions on Using the Filter

### ISSUE THREAD

**Issue by meenbeese** [Sjord/tutanospam#1]
Hello, I saw this project on your website and as someone who recently switched to Tutanota and is suffering from spam emails as well, I want to give this a try myself.

Can you add some documentation in the README here or on your article to get people started with using it, or even package it as Chrome extension at some point?

It would help me and others who are not well versed with JavaScript. Thanks!

**Comment by Sjord** [comment]
I have made a pull request (#2) with these instructions:

> # Install
> 
> 1. Run `git clone https://github.com/Sjord/tutanospam.git`.
> 2. In Chrome, go to the extensions page at `chrome://extensions/` or in the hamburger menu, "Extensions", "Manage Extensions".
> 3. Enable "Developer mode" slider in the top-right corner.
> 4. Click the "Load unpacked" button.
> 5. Navigate to the tutanospam directory from step 1 and click "Select".
> 
> # Usage
> 
> 1. Open Tutanota. The extension will learn from your messages as soon as the Tutanota app loads.
> 2. In the top bar, two additional buttons appear, "Select spam" and "Move to spam".
> 3. Click "Select spam" to select all messages that the filter thinks are spam.
> 4. Click "Move to spam" to move the selected messages to spam.

Is that what you are looking for?

**Comment by meenbeese** [comment]
Yes, that's exactly what I'm looking for. I can't wait to try the filter and see if it works for me. Thanks for building it and responding so quickly.
